// Usage: `node custom-reporter.ts`
import { copyFile, readFile, writeFile } from 'fs/promises';
import { glob } from 'glob';

/**
 * SDD-L10, T8 + T9. Two fixes in this file.
 *
 * **The glob API.** `glob` was never a declared dependency — it arrived transitively through jest@29,
 * which pinned 7.2.3, whose callback signature this script used. Declaring it explicitly at ^11
 * (T8, so `custom-docs.ts` stops silently doing nothing) removes that callback API entirely, so this
 * script had to move to the promise form with it. Leaving it on an undeclared transitive dependency
 * was the actual problem: the version was decided by Jest's lockfile, and Jest 30 drops `glob`
 * altogether.
 *
 * **The favicon.** It was read with `readFile(path, 'utf8')` and written back — decoding a PNG as
 * UTF-8 replaces every byte that is not valid UTF-8 with U+FFFD, so the 1,572-byte source landed as
 * a 445-byte file that no browser could render. Copying the file is both correct and simpler than
 * the read/write pair it replaces.
 *
 * SDD-L11-T5. Typed, and the `noindex` injection is now asserted rather than assumed. These scripts
 * consume HTML produced by another tool, so their boundary is a regex against someone else's markup:
 * when the generator's output shifts, a replacement stops matching and says nothing. That is not
 * hypothetical — `custom-docs` did exactly that for months (see its header), and the guard that
 * failed was this same one.
 */
const NOINDEX_META = '<meta name="robots" content="noindex">';

const stampCoverageReport = (html: string): string => {
    let replaced = html.replace(
        /Code coverage generated by\n\s*<a href="https:\/\/istanbul\.js\.org\/" target="_blank" rel="noopener noreferrer">istanbul<\/a>\n\s*(.*)\n\s*<\/div>/g,
        `Code coverage automatically generated by Xabier Lameiro on ${new Date().toLocaleString()}`,
    );

    replaced = replaced.replace(
        /<div class='pad1'>\n\s*<h1>(.*)All files/g,
        "<div class='pad1'><h1><a href='/'>Return</a></h1></h1><h1><a href='/'>All tests</a>",
    );

    replaced = replaced.replace(/<title>(.*)<\/title>/, '<title>Code coverage by Xabier Lameiro</title>');

    // SDD-002 D1: auto-generated report pages must never be indexed
    replaced = replaced.replace(/<head>/, `<head>${NOINDEX_META}`);

    replaced = replaced.replace(
        /(.*)<link rel="shortcut icon" (.*)\s* href="(.*)" \/>/,
        '<link rel="shortcut icon" type="image/x-icon" href="https://pre.xabierlameiro.com/favicon.png">',
    );

    replaced = replaced.replace(/\.pad1 { padding: 10px; }/, '.pad1 { padding: 10px; width: 100%; overflow: scroll; }');

    return replaced;
};

/**
 * @description Fail loudly if the indexing guard did not land. Istanbul emits `<head>` on every page
 * it generates, so a miss means the generator changed and the SDD-002 D1 guard silently lapsed —
 * exactly the failure this file exists to prevent. CSS files are stamped too but have no `<head>`.
 */
const assertNoindex = (path: string, html: string): void => {
    if (!path.endsWith('.html')) return;
    if (html.includes(NOINDEX_META)) return;
    throw new Error(
        `${path}: the noindex guard did not apply — istanbul's HTML no longer matches the <head> ` +
            `replacement in custom-reporter.ts. Fix the pattern; do not ship an indexable report.`,
    );
};

const run = async (): Promise<void> => {
    const files = await glob('public/coverage/**/*.?(html|css)');

    await Promise.all(
        files.map(async (path) => {
            const data = await readFile(path, 'utf8');
            const stamped = stampCoverageReport(data);
            assertNoindex(path, stamped);
            await writeFile(path, stamped, 'utf-8');
        }),
    );

    await copyFile('public/favicon.png', 'public/coverage/favicon.png');
};

run().catch((err: unknown) => {
    console.error('Failed to post-process the coverage report:', err);
    process.exitCode = 1;
});
