name: Playwright Tests
on:
    push:
        branches: [dev, master]
    pull_request:
        branches: [dev, master]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  allways-auth: true
                  registry-url: '@xabierlameiro:registry=https://npm.pkg.github.com/'
                  auth: ${{ secrets.AUTH_TOKEN }}
                  node-version: 18
            - name: Install dependencies
              run: yarn install
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
