name: Test end-to-end with Playwright
on:
    push:
        branches: [dev]
    # pull_request:
    #     branches: [dev, master]
jobs:
    wait-for-vercel-deployment:
        runs-on: ubuntu-22.04
        steps:
            - name: Wait for Vercel deployment
              uses: UnlyEd/github-action-await-vercel@v1.2.39
              id: await-vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              with:
                  deployment-url: the-last-dance-git-dev-xlameiro.vercel.app
                  timeout: 10 # Wait for 10 seconds before failing
            - name: Display deployment status
              run: 'echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}'
    test:
        timeout-minutes: 60
        needs: wait-for-vercel-deployment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
