name: Test end-to-end with Playwright
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
jobs:
    wait-for-deployment:
        uses: ./vercel-deployment.yml
        if: (github.event_name == 'push' || github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]')
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        test:
            timeout-minutes: 60
            needs: wait-for-deployment
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v3
                - uses: actions/setup-node@v3
                  with:
                      node-version: 18
                - name: Install dependencies
                  run: |
                      echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                      echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                      yarn install
                  env:
                      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                - name: Install Playwright Browsers
                  run: npx playwright install --with-deps
                - name: Run Playwright tests
                  run: npx playwright test
                - uses: actions/upload-artifact@v3
                  if: always()
                  with:
                      name: playwright-report
                      path: playwright-report/
                      retention-days: 30
