name: Testing end to end with Playwright
on:
    push:
    pull_request:

jobs:
    wait-for-vercel-deployment:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: UnlyEd/github-action-await-vercel@v1
              id: await-vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              with:
                  deployment-url: pre.xabierlameiro.com
                  timeout: 10 # Wait for 10 seconds before failing
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
