name: Test end-to-end with Playwright
on:
    push:
        branches:
    pull_request:
        branches:
jobs:
    wait-for-vercel-deployment:
        runs-on: ubuntu-22.04
        outputs:
            vercel-deployment-url: the-last-dance-git-dev-xlameiro.vercel.app
        steps:
            - name: Sleep to wait for new deployment is created
              run: sleep 20
            - name: Wait for Vercel deployment
              uses: UnlyEd/github-action-await-vercel@v1.2.39
              id: await-vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              with:
                  deployment-url: the-last-dance-git-dev-xlameiro.vercel.app
                  timeout: 600

            - name: Display deployment status
              run: 'echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}'
    testing-end-to-end:
        timeout-minutes: 60
        needs: wait-for-vercel-deployment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
