name: Workflow Post-Deploy
on:
    push:
        branches: [master]

permissions:
  contents: read

jobs:
    lighthouse:
        name: Lighthouse
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.20.0
                  cache: npm
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  npm install --legacy-peer-deps
            - name: Execute Lighthouse
              run: |
                  sleep 10m
                  npm run lighthouse-report
            - name: Checkout performance-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/performance-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: performance-report
            - name: Copy output folder and publish
              run: |
                  cd performance-report
                  cp -r ../lighthouse .
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add .
                  git commit -m "Update performance-report"
                  git push origin main
