name: Workflow Post-Deploy
on:
    push:
        branches: [master]
jobs:
    lighthouse:
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install --frozen-lockfile
            - name: Execute Lighthouse
              run: |
                    # Deploy to Vercel here (replace with the appropriate command)
                    # Wait for the deployment to finish
                    DEPLOYMENT_ID=$(vercel deploy --prod | grep 'https://your-vercel-app.vercel.app' | cut -d ' ' -f 2)
                    STATUS=""
                    while [[ "$STATUS" != "READY" ]]; do
                      sleep 30s
                      STATUS=$(vercel deployments ls $DEPLOYMENT_ID --json | jq -r '.[0].state')
                    done
                  yarn lighthouse-report
            - name: Checkout performance-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/performance-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: performance-report
            - name: Copy output folder and publish
              run: |
                  cd performance-report
                  cp -r ../lighthouse .
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add .
                  git commit -m "Update performance-report"
                  git push origin main
