name: Pre Deploy on Vercel - Unit Tests in Development Environment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches: [dev, master]
jobs:
    Pre-Deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/dev'
        env:
            NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install
            - name: Run unit tests
              run: npm run test
            - name: Install Vercel CLI
              run: npm install --global vercel@canary
            - name: Deploy Project Artifacts to Vercel
              run: |
                  vercel deploy --token=${{ secrets.VERCEL_TOKEN }} >> deploy-url.txt
                  echo URL=$(cat deploy-url.txt) >> $GITHUB_ENV
            - name: Print URL of current deployment
              run: echo ${{ env.URL }}
