name: Dev workflow
on:
    push:
        branches: [dev]
jobs:
    avoid_reduncy:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous redundant workflow runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ secrets.TOKEN_GITHUB }}
    install_dependencies:
        runs-on: ubuntu-latest
        env:
            NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn
            - name: Restore cache dependencias
              uses: actions/cache@v2
              with:
                  path: ~/.cache/yarn
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install --frozen-lockfile
            - name: Save cache node_modules
              uses: actions/cache@v2
              with:
                  path: ~/.cache/yarn
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn
            - name: Linter
              if: false
              run: yarn && yarn run lint

    unit-tests:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/dev'
        env:
            NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn
            - name: Install dependencies
              if: false
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install --frozen-lockfile
            - name: Run unit tests
              if: false
              run: yarn run coverage
            - name: Checkout unit-report repository
              if: false
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/unit-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: unit-report
            - name: Copy unit1 test coverage and publish
              if: false
              run: |
                  cd unit-report
                  cp -r ../public/coverage/ .
                  git config --global user.email "xabier.lameiro@gmail.com"
                  git config --global user.name "xabierlameiro.com"
                  git add .
                  git commit -m "Update unit-report"
                  git push origin main
            - name: Generate documentation
              if: false
              run: yarn run jsdoc
            - name: Checkout doc repository
              if: false
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/doc-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: doc
            - name: Copy documentation and publish
              if: false
              run: |
                  cd doc
                  cp -r ../public/docs/ .
                  git config --global user.email "xabier.lameiro@gmail.com"
                  git config --global user.name "xabierlameiro.com"
                  git add .
                  git commit -m "Update doc-report"
                  git push origin main
            - name: Checkout stb-report repository
              if: false
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/stb-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: stb-report
            - name: Copy storybook and publish
              if: false
              run: |
                  yarn build-storybook
                  cd stb-report
                  cp -r ../storybook-static/ .
                  git config --global user.email "xabier.lameiro@gmail.com"
                  git config --global user.name "xabierlameiro.com"
                  git add .
                  git commit -m "Update stb-report"
                  git push origin main
            - name: Install Vercel CLI
              if: false
              run: npm install --global vercel@canary
            - name: Trigger Vercel Deployment
              if: false
              env:
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  vercel deploy --token=${{ secrets.VERCEL_TOKEN }} >> deploy-url.txt
                  echo URL=$(cat deploy-url.txt) >> $GITHUB_ENV
                  echo NEXT_PUBLIC_DOMAIN=$(cat deploy-url.txt) >> $GITHUB_ENV
            - name: Install Playwright Browsers
              if: false
              run: npx playwright install --with-deps chromium
            - name: Run end-to-end tests
              if: false
              id: e2e
              run: |
                  yarn test:e2e:report
            - name: Checkout e2e-report repository
              if: false
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/e2e-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: e2e-report
            - name: Copy playwright-report/index.html to e2e-report/index.html
              if: false
              run: |
                  cd e2e-report
                  cp -r ../playwright-report/index.html index.html
                  git config --global user.email "xabier.lameiro@gmail.com"
                  git config --global user.name "xabierlameiro.com"
                  git add .
                  git commit -m "Update e2e-report"
                  git push origin main
