name: Workflow Pre-Deploy
on:
    push:
        branches: [dev]

permissions:
  contents: write

jobs:
    cancel_redundancy:
        name: Cancel Redundant Workflow Runs
        runs-on: ubuntu-22.04
        steps:
            - name: Cancel previous redundant workflow runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ secrets.TOKEN_GITHUB }}
    code_checking:
        name: Linting
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.20.0
                  cache: npm
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  npm install --legacy-peer-deps
            - name: Linter
              run: npm run lint
    testing:
        name: Testing
        runs-on: ubuntu-22.04
        env:
            NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            NEXT_PUBLIC_ENV: 'preview'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.20.0
                  cache: npm
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  npm install --legacy-peer-deps
            - name: Run unit tests
              run: npm run coverage
            - name: Checkout unit-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/unit-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: unit-report
            - name: Copy report coverage folder and publish
              run: |
                  cd unit-report
                  cp -r ../public/coverage/ .
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add .
                  git commit -m "Update unit-report"
                  git push origin main
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps chromium
              env:
                  DEBIAN_FRONTEND: noninteractive
            - name: Run dev server
              run: npm run dev &
            - name: Wait for dev server to be ready
              run: npx wait-on http://localhost:3000
            - name: Run end-to-end tests
              run: |
                  npm run test:e2e:report
            - name: Checkout e2e-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/e2e-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: e2e-report
            - name: Copy playwright-report/index.html to e2e-report/index.html
              run: |
                  cd e2e-report
                  cp -r ../playwright-report/index.html index.html
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add .
                  git commit -m "Update e2e-report"
                  git push origin main
    documentation:
        name: Documenting
        runs-on: ubuntu-22.04
        env:
            NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.20.0
                  cache: npm
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  npm install --legacy-peer-deps
            - name: Generate documentation
              run: npm run jsdoc
            - name: Checkout doc repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/doc-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: doc
            - name: Copy documentation and publish
              run: |
                  cd doc
                  cp -r ../public/docs/ .
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add .
                  git commit -m "Update doc-report"
                  git push origin main
            - name: Checkout stb-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/stb-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: stb-report
            - name: Copy storybook and publish
              run: |
                  npm run build-storybook
                  cd stb-report
                  cp -r ../storybook-static/ .
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add .
                  git commit -m "Update stb-report"
                  git push origin main
    version:
        name: Versioning
        runs-on: ubuntu-22.04
        needs: [code_checking, testing, documentation]
        steps:
            - name: Checkout version repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.TOKEN_GITHUB }}
            - name: Version
              id: version
              uses: paulhatch/semantic-version@v5.0.2
              with:
                  version_format: '${major}.${minor}.${patch}'
                  major_pattern: 'MAJOR -'
                  minor_pattern: 'MINOR -'
            - name: Update version in package.json and add tag
              run: |
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  npm version ${{ steps.version.outputs.version }}
                  git push --follow-tags

    deploy:
        name: Trigger deploy on preview environment
        runs-on: ubuntu-22.04
        needs: [version]
        steps:
            - name: Deploy to Vercel
              run: |
                  curl -X POST https://api.vercel.com/v1/integrations/deploy/${{ secrets.PRJ }}
