name: Dev workflow
on:
    push:
        branches: [dev]
jobs:
    unit-tests-and-deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/dev'
        env:
            NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn
            - name: Install dependencies
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
                  echo "@xabierlameiro:registry=https://npm.pkg.github.com/" >> ~/.npmrc
                  yarn install --frozen-lockfile
            - name: Linter
              if: false
              run: yarn run lint
            - name: Run unit tests
              run: yarn run coverage
            - name: Checkout unit-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/unit-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: unit-report
            - name: Copy unit1 test coverage and publish
              run: |
                  cd unit-report
                  cp -r ../public/coverage/ coverage/
                  git config --global user.email "xabier.lameiro@gmail.com"
                  git config --global user.name "xabierlameiro.com"
                  git add .
                  git commit -m "Update unit-report"
                  git push origin main
            - name: Publish coverage report
              if: false
              env:
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_COVERAGE_PROJECT_ID }}
              run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
            - name: Publish storybook
              if: false
              env:
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}
              run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
            - name: Install Vercel CLI
              run: npm install --global vercel@canary
            - name: Trigger Vercel Deployment
              if: false
              env:
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  vercel deploy --token=${{ secrets.VERCEL_TOKEN }} >> deploy-url.txt
                  echo URL=$(cat deploy-url.txt) >> $GITHUB_ENV
                  echo NEXT_PUBLIC_DOMAIN=$(cat deploy-url.txt) >> $GITHUB_ENV
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps chromium
            - name: Run end-to-end tests
              id: e2e
              run: |
                  yarn test:e2e:report
            - name: Checkout e2e-report repository
              uses: actions/checkout@v3
              with:
                  repository: xabierlameiro/e2e-report
                  token: ${{ secrets.TOKEN_GITHUB }}
                  path: e2e-report
            - name: Copy playwright-report/index.html to e2e-report/index.html
              run: |
                  cd e2e-report
                  cp -r ../playwright-report/index.html index.html
                  git config --global user.email "xabier.lameiro@gmail.com"
                  git config --global user.name "xabierlameiro.com"
                  git add .
                  git commit -m "Update e2e-report"
                  git push origin main
